name: Deploy CVE.ICU

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: "0 */4 * * *" 

jobs:
  deploy-book:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        architecture: 'x64'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdebuginfod1 libdebuginfod-common libelf-dev libdebuginfod-dev jupyter unzip parallel
        sudo apt-get install -f
        python -m pip install --upgrade pip
        python -m pip install --prefer-binary -r requirements.txt
        python -m pip install --prefer-binary nbconvert

    - name: Grab Needed Data
      run: |
        wget -q  https://nvd.handsonhacking.org/nvd.jsonl
        ls -lh 

    - name: Run Notebooks in Parallel
      env:
        GH_TOKEN:  ${{ secrets.GH_TOKEN }}
      run: |
        NOTEBOOKS="CVEAll.ipynb CVEAll-Interactive.ipynb CVE2016.ipynb CVE2017.ipynb CVE2018.ipynb CVE2019.ipynb CVE2020.ipynb CVE2021.ipynb CVE2022.ipynb CVE2023.ipynb CVE2024.ipynb CVE2025.ipynb CVECalendar.ipynb CVEGrowth.ipynb CVECVSS.ipynb CVECNA.ipynb CVECWE.ipynb CVECPE.ipynb"
        printf "%s\n" $NOTEBOOKS | xargs -P 4 -n 1 jupyter nbconvert --to notebook --inplace --execute

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
          default_author: github_actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the book
      run: |
        jupyter-book build .

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        cname: cve.icu
